apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: galera
spec:
  selector:
    matchLabels:
      app: galera
  serviceName: "galera"
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: galera
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: init-config
        command: ['/bin/sh', '/etc/mysql/conf.d/init.sh']
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DATADIR
          value: /data/db
        volumeMounts:
        - name: mysql
          mountPath: /data
        - name: conf
          mountPath: /etc/mysql/conf.d
      containers:
      - name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 4444
          name: sst
        - containerPort: 4567
          name: replication
        - containerPort: 4567
          protocol: UDP
          name: replicationudp
        - containerPort: 4568
          name: ist
        env:
        - name: MYSQL_ROOT_HOST
          value: "localhost"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "yes"
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-ec", "echo [ ON = $(mysql -e \"SHOW STATUS LIKE 'wsrep_ready';\" -N -B | sed 's/.*ON/ON/') ]" ]
          initialDelaySeconds: 30
        livenessProbe:
          exec:
            command:
            - mysql
            - -e
            - "SHOW DATABASES;"
          # might need to be tweaked for large initial state transfers
          initialDelaySeconds: 60
        volumeMounts:
        - name: mysql
          mountPath: /data
        - name: conf
          mountPath: /etc/mysql/conf.d
      - name: metrics
        env:
        - name: DATA_SOURCE_NAME
          value: root@(localhost:3306)/
        ports:
        - containerPort: 9104
      volumes:
      - name: conf
        configMap:
          name: conf-d
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
